//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int IDbooking { get; set; }
        public Nullable<int> Numpeople { get; set; }
        public Nullable<int> Numchild { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public byte[] States { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string IDuser { get; set; }
        public Nullable<int> IDroom { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string FullName { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SingleRoom SingleRoom { get; set; }
    }
}
