//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryRoom()
        {
            this.SingleRooms = new HashSet<SingleRoom>();
        }
    
        public int IDcategory { get; set; }
        public string Imgcategory { get; set; }
        public string Namecategory { get; set; }
        public string discriptioncategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SingleRoom> SingleRooms { get; set; }
    }
}
