//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkout
    {
        public int IDcheckout { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<bool> States { get; set; }
        public string IDuser { get; set; }
        public Nullable<int> IDroom { get; set; }
        public Nullable<System.DateTime> Datecheckout { get; set; }
        public Nullable<double> Totalprice { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual SingleRoom SingleRoom { get; set; }
    }
}
