//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RateRoom()
        {
            this.SingleRooms = new HashSet<SingleRoom>();
        }
    
        public int IDrate { get; set; }
        public Nullable<int> IDroom { get; set; }
        public string IDuser { get; set; }
        public string comment { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SingleRoom> SingleRooms { get; set; }
    }
}
