//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_7
{
    using System;
    using System.Collections.Generic;
    
    public partial class SingleRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SingleRoom()
        {
            this.Bookings = new HashSet<Booking>();
            this.checkouts = new HashSet<checkout>();
        }
    
        public int IDroom { get; set; }
        public string roomNumber { get; set; }
        public string discriptionRoom { get; set; }
        public Nullable<int> quntity { get; set; }
        public Nullable<int> price { get; set; }
        public string ImgRoom1 { get; set; }
        public string ImgRoom2 { get; set; }
        public string ImgRoom3 { get; set; }
        public string ImgRoom4 { get; set; }
        public Nullable<int> IDRate { get; set; }
        public Nullable<int> IDcategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual CategoryRoom CategoryRoom { get; set; }
        public virtual RateRoom RateRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checkout> checkouts { get; set; }
    }
}
